- hosts: gitserver
  vars_files:
    - password-vars.yaml
  tasks:
    - name: create htpasswd
      tags: create
      #include_vars:
      #  file: password-vars.yaml
      shell: "echo {{ USER }}:'{{ PASS }}' >> {{ DIR }}"
    - name: update htpasswd
      tags: update
      replace:
        path: "{{ DIR }}"
        regexp: '{{ USER }}.*'
        replace: '{{ USER }}:{{ PASS }}'
      #shell: "sed -i 's/{{ USER }}:.*/{{ USER }}:{{ PASS }}/g' /home/git/.passwd"
    - name: delete htpasswd
      tags: delete
      #replace:
        #path: "{{ DIR }}/.passwd"
        #regexp: '{{ USER }}.*'
        #replace: ''      
      shell: "sed -i '/{{ USER }}/d' {{ DIR }}"      